// Generated by Wrangler on Tue Jul 02 2024 23:59:00 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	NEXTAUTH_URL: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	DB: D1Database;
}
